[tool.polnet]
out_dir = "/mnt/lustre-grete/projects/nim00020/sage/data/simulation/integrated/testing/synapse"
ntomos = 3
voi_vsize = 10 
voi_shape = [630, 630, 184]

# feature lists
membranes_list = [
    "in_mbs/ellipse.mbs",
]
helix_list = [
    "in_helix/mt.hns",
    "in_helix/actin.hns"
]
proteins_list = [
    "in_10A/6qzp_10A.pns"
]
membrane_proteins_list = [
    "in_10A/mb_7tmr_10A.pms",
    "in_10A/mb_1l4a_10A.pms",
    "in_10A/mb_7udb_10A.pms",
    "in_10A/mb_8sbe_10A.pms",
    "in_10A/mb_9brz_10A.pms",
    "in_10A/mb_VMAT_10A.pms",
    "in_10A/mb_VGLUT_10A.pms",
    "in_10A/mb_Synaptotagmin_10A.pms",
    "in_10A/mb_Synaptophysin_10A.pms",
    "in_10A/mb_rab3_10A.pms"
]
# feature selection
disable_cytosolic_proteins = true

[tool.faket]
base_dir = "/mnt/lustre-grete/projects/nim00020/sage/data/simulation/integrated/test_dataset"
simulation_index = 2
detector_snr = [0.4, 0.5]
tilt_start = -60
tilt_stop = 60
tilt_step = 2
